mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  fallback:
  - https://1.1.1.1/dns-query
  - https://8.8.8.8/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
proxies:
- name: github.com/freefq - 俄罗斯  1
  type: ss
  server: 185.242.86.156
  port: 54170
  cipher: chacha20-ietf-poly1305
  password: 36ZCHeabUSfKjfQEvJ4HDV
  udp: true
- name: github.com/freefq - 印度  2
  type: vmess
  server: 202.78.162.5
  port: 443
  uuid: 2ff97c6d-8557-42a4-b43f-19c77c5959ea
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  tls: true
  ws-opts:
    path: /@forwardv2ray
    headers:
      Host: irsoft.sytes.net
- name: github.com/freefq - 美国CloudFlare公司CDN节点 4
  type: vmess
  server: www.darkroom.lol
  port: 8080
  uuid: 22826b44-5c1a-4b4b-dbaa-83a2e8bd95f0
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: www.darkroom.lol
- name: github.com/freefq - 波兰  5
  type: ss
  server: 193.243.147.128
  port: 40368
  cipher: aes-256-gcm
  password: 7BcLdsO1WweoGD0X
  udp: true
- name: github.com/freefq - 美国CloudFlare公司CDN节点 6
  type: vmess
  server: server31.beheshtbaneh.com
  port: 8880
  uuid: 4154143c-bbba-47a4-9f79-c2ed087cbcc9
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: server31.beheshtbaneh.com
- name: github.com/freefq - 广东省移动 7
  type: vmess
  server: data-us-v1.shwjfkw.cn
  port: 20401
  uuid: b1478e24-4916-3abe-8f17-15931012ecbe
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /debian
    headers:
      Host: data-us-v1.shwjfkw.cn
- name: github.com/freefq - 广东省江门市移动 8
  type: ss
  server: service.ouluyun9803.com
  port: 20003
  cipher: chacha20-ietf-poly1305
  password: d6105bbd-be0d-45b2-82ad-31fd1071c1d2
  udp: true
- name: github.com/freefq - 美国CloudFlare公司CDN节点 9
  type: vmess
  server: 104.21.82.183
  port: 8880
  uuid: 5a7021e0-26b4-45d6-b175-fe551601ca97
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: server26.beheshtbaneh.com
- name: github.com/freefq - 广东省江门市移动 11
  type: ss
  server: service.ouluyun9803.com
  port: 26667
  cipher: chacha20-ietf-poly1305
  password: d6105bbd-be0d-45b2-82ad-31fd1071c1d2
  udp: true
- name: github.com/freefq - 广东省江门市移动 12
  type: ss
  server: service.ouluyun9803.com
  port: 20005
  cipher: chacha20-ietf-poly1305
  password: d6105bbd-be0d-45b2-82ad-31fd1071c1d2
  udp: true
- name: github.com/freefq - 美国Fastly全球Anycast节点 13
  type: vmess
  server: gov.uk
  port: 443
  uuid: 77848824-93b7-4b89-ffd0-e91afff406ce
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  tls: true
  ws-opts:
    path: /77848824
    headers:
      Host: zheshiscp.com
- name: github.com/freefq - 美国CloudFlare节点 14
  type: vmess
  server: server32.beheshtbaneh.com
  port: 8880
  uuid: 044ba8ed-7285-472a-bc14-fb91dc6be4c9
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: server32.beheshtbaneh.com
- alterId: 0
  cipher: auto
  name: 防范境外势力渗透
  network: tcp
  port: 80
  server: 127.0.0.53
  tls: false
  type: vmess
  uuid: 88888888-8888-8888-8888-888888888888
- alterId: 0
  cipher: auto
  name: '防范境外势力渗透 #1'
  network: tcp
  port: 81
  server: 127.0.0.53
  tls: false
  type: vmess
  uuid: 88888888-8888-8888-8888-888888888888
- alterId: 0
  cipher: auto
  name: '防范境外势力渗透 #2'
  network: tcp
  port: 82
  server: 127.0.0.53
  tls: false
  type: vmess
  uuid: 88888888-8888-8888-8888-888888888888
- alterId: 0
  cipher: auto
  name: '防范境外势力渗透 #3'
  network: tcp
  port: 83
  server: 127.0.0.53
  tls: false
  type: vmess
  uuid: 88888888-8888-8888-8888-888888888888
- alterId: 0
  cipher: auto
  name: '防范境外势力渗透 #4'
  network: tcp
  port: 84
  server: 127.0.0.53
  tls: false
  type: vmess
  uuid: 88888888-8888-8888-8888-888888888888
- alterId: 0
  cipher: auto
  name: '防范境外势力渗透 #5'
  network: tcp
  port: 85
  server: 127.0.0.53
  tls: false
  type: vmess
  uuid: 88888888-8888-8888-8888-888888888888
- alterId: 0
  cipher: auto
  name: '防范境外势力渗透 #6'
  network: tcp
  port: 86
  server: 127.0.0.53
  tls: false
  type: vmess
  uuid: 88888888-8888-8888-8888-888888888888
- alterId: 0
  cipher: auto
  name: '防范境外势力渗透 #7'
  network: tcp
  port: 87
  server: 127.0.0.53
  tls: false
  type: vmess
  uuid: 88888888-8888-8888-8888-888888888888
- alterId: 0
  cipher: auto
  name: '防范境外势力渗透 #8'
  network: tcp
  port: 88
  server: 127.0.0.53
  tls: false
  type: vmess
  uuid: 88888888-8888-8888-8888-888888888888
- alterId: 0
  cipher: auto
  name: '防范境外势力渗透 #9'
  network: tcp
  port: 89
  server: 127.0.0.53
  tls: false
  type: vmess
  uuid: 88888888-8888-8888-8888-888888888888
- cipher: aes-256-cfb
  name: 'tg频道:@ripaojiedian #1'
  password: amazonskr05
  port: 443
  server: 63.180.254.10
  type: ss
- alterId: 2
  cipher: auto
  name: 🇭🇰 香港|@ripaojiedian
  port: 30807
  server: v10.hdacd.com
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
- name: 🇭🇰HK_1|3.8MB/s
  network: tcp
  password: d84665c37878196ecf983cf6910e3b44
  port: 53018
  server: 18.181.199.223
  skip-cert-verify: true
  sni: www.nintendogames.net
  type: trojan
- name: 香港4|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 11031
  server: 95.40.4.37
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  type: trojan
- name: 🇭🇰HK_2|3.4MB/s
  network: tcp
  password: BxceQaOe
  port: 50712
  server: 18.183.163.141
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  type: trojan
- name: 日本|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 30022
  server: 43.207.209.201
  skip-cert-verify: true
  sni: t.me%252Fripaojiedian
  type: trojan
- name: 日本2|@ripaojiedian
  network: tcp
  password: d84665c37878196ecf983cf6910e3b44
  port: 11541
  server: 43.198.204.47
  skip-cert-verify: true
  sni: www.nintendogames.net
  type: trojan
- name: 日本3|@ripaojiedian
  network: tcp
  password: d84665c37878196ecf983cf6910e3b44
  port: 8066
  server: 18.181.199.223
  skip-cert-verify: true
  sni: www.nintendogames.net
  type: trojan
- name: 新加坡|@ripaojiedian
  network: tcp
  password: d84665c37878196ecf983cf6910e3b44
  port: 2511
  server: 18.162.232.155
  skip-cert-verify: true
  sni: www.nintendogames.net
  type: trojan
- name: 新加坡2|@ripaojiedian
  network: tcp
  password: d84665c37878196ecf983cf6910e3b44
  port: 3842
  server: 18.181.199.223
  skip-cert-verify: true
  sni: www.nintendogames.net
  type: trojan
- name: 新加坡3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 10478
  server: 43.199.217.71
  skip-cert-verify: true
  sni: t.me%252Fripaojiedian
  type: trojan
- name: 美国2|@ripaojiedian
  network: tcp
  password: d84665c37878196ecf983cf6910e3b44
  port: 6604
  server: 18.162.232.155
  skip-cert-verify: true
  sni: www.nintendogames.net
  type: trojan
- name: 美国3|@ripaojiedian
  network: tcp
  password: BxceQaOe
  port: 2702
  server: 95.40.68.150
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  type: trojan
- alterId: 0
  cipher: auto
  name: 🇺🇸 美国4|@ripaojiedian
  port: 180
  server: 82.198.246.250
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
- name: 🇺🇸US_1|1.4MB/s
  network: tcp
  password: BxceQaOe
  port: 2520
  server: 95.40.4.37
  skip-cert-verify: true
  sni: t.me/ripaojiedian
  type: trojan
  udp: true
- name: 🇵🇱PL_1|1.1MB/s
  network: ws
  password: humanity
  port: 443
  server: 172.66.44.211
  skip-cert-verify: true
  sni: www.creationlong.org
  type: trojan
  udp: true
  ws-opts:
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like
        Gecko) Chrome/53.0.2785.143 Safari/537.36
    path: /assignment
- name: JP_speednode_0022
  password: d84665c37878196ecf983cf6910e3b44
  port: 1180
  server: 18.181.199.223
  skip-cert-verify: true
  sni: www.nintendogames.net
  type: trojan
  udp: true
- name: JP_speednode_0023
  password: BxceQaOe
  port: 4099
  server: 18.183.163.141
  skip-cert-verify: true
  sni: t.me%252Fripaojiedian
  type: trojan
  udp: true
- name: US_speednode_0054
  password: BxceQaOe
  port: 17801
  server: 95.40.68.192
  skip-cert-verify: true
  sni: t.me%2Fripaojiedian
  type: trojan
  udp: true
proxy-groups:
- name: AUTO
  type: url-test
  proxies:
  - github.com/freefq - 俄罗斯  1
  - github.com/freefq - 印度  2
  - github.com/freefq - 美国CloudFlare公司CDN节点 4
  - github.com/freefq - 波兰  5
  - github.com/freefq - 美国CloudFlare公司CDN节点 6
  - github.com/freefq - 广东省移动 7
  - github.com/freefq - 广东省江门市移动 8
  - github.com/freefq - 美国CloudFlare公司CDN节点 9
  - github.com/freefq - 广东省江门市移动 11
  - github.com/freefq - 广东省江门市移动 12
  - github.com/freefq - 美国Fastly全球Anycast节点 13
  - github.com/freefq - 美国CloudFlare节点 14
  - 防范境外势力渗透
  - '防范境外势力渗透 #1'
  - '防范境外势力渗透 #2'
  - '防范境外势力渗透 #3'
  - '防范境外势力渗透 #4'
  - '防范境外势力渗透 #5'
  - '防范境外势力渗透 #6'
  - '防范境外势力渗透 #7'
  - '防范境外势力渗透 #8'
  - '防范境外势力渗透 #9'
  - 'tg频道:@ripaojiedian #1'
  - 🇭🇰 香港|@ripaojiedian
  - 🇭🇰HK_1|3.8MB/s
  - 香港4|@ripaojiedian
  - 🇭🇰HK_2|3.4MB/s
  - 日本|@ripaojiedian
  - 日本2|@ripaojiedian
  - 日本3|@ripaojiedian
  - 新加坡|@ripaojiedian
  - 新加坡2|@ripaojiedian
  - 新加坡3|@ripaojiedian
  - 美国2|@ripaojiedian
  - 美国3|@ripaojiedian
  - 🇺🇸 美国4|@ripaojiedian
  - 🇺🇸US_1|1.4MB/s
  - 🇵🇱PL_1|1.1MB/s
  - JP_speednode_0022
  - JP_speednode_0023
  - US_speednode_0054
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 80
- name: PROXY
  type: select
  proxies: &id001
  - AUTO
  - DIRECT
  - github.com/freefq - 俄罗斯  1
  - github.com/freefq - 印度  2
  - github.com/freefq - 美国CloudFlare公司CDN节点 4
  - github.com/freefq - 波兰  5
  - github.com/freefq - 美国CloudFlare公司CDN节点 6
  - github.com/freefq - 广东省移动 7
  - github.com/freefq - 广东省江门市移动 8
  - github.com/freefq - 美国CloudFlare公司CDN节点 9
  - github.com/freefq - 广东省江门市移动 11
  - github.com/freefq - 广东省江门市移动 12
  - github.com/freefq - 美国Fastly全球Anycast节点 13
  - github.com/freefq - 美国CloudFlare节点 14
  - 防范境外势力渗透
  - '防范境外势力渗透 #1'
  - '防范境外势力渗透 #2'
  - '防范境外势力渗透 #3'
  - '防范境外势力渗透 #4'
  - '防范境外势力渗透 #5'
  - '防范境外势力渗透 #6'
  - '防范境外势力渗透 #7'
  - '防范境外势力渗透 #8'
  - '防范境外势力渗透 #9'
  - 'tg频道:@ripaojiedian #1'
  - 🇭🇰 香港|@ripaojiedian
  - 🇭🇰HK_1|3.8MB/s
  - 香港4|@ripaojiedian
  - 🇭🇰HK_2|3.4MB/s
  - 日本|@ripaojiedian
  - 日本2|@ripaojiedian
  - 日本3|@ripaojiedian
  - 新加坡|@ripaojiedian
  - 新加坡2|@ripaojiedian
  - 新加坡3|@ripaojiedian
  - 美国2|@ripaojiedian
  - 美国3|@ripaojiedian
  - 🇺🇸 美国4|@ripaojiedian
  - 🇺🇸US_1|1.4MB/s
  - 🇵🇱PL_1|1.1MB/s
  - JP_speednode_0022
  - JP_speednode_0023
  - US_speednode_0054
- name: GLOBAL
  type: select
  proxies: *id001
rules:
- DOMAIN-SUFFIX,local,DIRECT
- DOMAIN-SUFFIX,localhost,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,192.168.0.0/16,DIRECT
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,PROXY
